//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class puntoencuentroEntities1 : DbContext
    {
        public puntoencuentroEntities1()
            : base("name=puntoencuentroEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_categorias> tb_categorias { get; set; }
        public DbSet<tb_lugar_voto> tb_lugar_voto { get; set; }
        public DbSet<tbcatlugar> tbcatlugar { get; set; }
        public DbSet<tbevento> tbevento { get; set; }
        public DbSet<tbgaleria> tbgaleria { get; set; }
        public DbSet<tbhorario> tbhorario { get; set; }
        public DbSet<tblugares> tblugares { get; set; }
        public DbSet<tbpago> tbpago { get; set; }
        public DbSet<tbpagolugares> tbpagolugares { get; set; }
        public DbSet<tbpersona> tbpersona { get; set; }
        public DbSet<tbtelefonos> tbtelefonos { get; set; }
        public DbSet<tbusuario> tbusuario { get; set; }
        public DbSet<tbvotousuario> tbvotousuario { get; set; }
        public DbSet<votos> votos { get; set; }
    }
}
