//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_categorias
    {
        public tb_categorias()
        {
            this.tbcatlugar = new HashSet<tbcatlugar>();
        }
    
        public int idcategorias { get; set; }
        public string nombre { get; set; }
        public Nullable<int> responsable { get; set; }
        public Nullable<int> padre { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<tbcatlugar> tbcatlugar { get; set; }
    }
}
