//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace punto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_lugar_voto
    {
        public decimal idvoto { get; set; }
        public string titulo { get; set; }
        public long num_votes { get; set; }
        public long total_score { get; set; }
        public decimal rating { get; set; }
        public Nullable<int> id { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual tblugares tblugares { get; set; }
    }
}
