//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace punto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcatlugar
    {
        public int idcatlugares { get; set; }
        public Nullable<int> idcategorias { get; set; }
        public Nullable<int> idlugares { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual tb_categorias tb_categorias { get; set; }
        public virtual tblugares tblugares { get; set; }
    }
}
