//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace punto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpago
    {
        public tbpago()
        {
            this.tbpagolugares = new HashSet<tbpagolugares>();
        }
    
        public int idpagos { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<tbpagolugares> tbpagolugares { get; set; }
    }
}
