//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace punto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class votos
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public int total_votes { get; set; }
        public int total_value { get; set; }
        public string used_ips { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
